=== sudarkoff/sudarkoff.github.com/poetry/poetry.dtd
<!ELEMENT album (author*)>
<!ATTLIST album name CDATA #REQUIRED>
<!ELEMENT author (verse*)>
<!ATTLIST author name CDATA #REQUIRED>
<!ELEMENT verse (title, date, text, link)>
<!ATTLIST verse id CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT link (#PCDATA)>

=== sudarkoff/sudarkoff.github.com/poetry/poetry.xml
<?xml version="1.0" encoding="KOI8-R" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="http://home.sudarkoff.com/poem2html.xsl"?>
<!DOCTYPE album SYSTEM "http://home.sudarkoff.com/poetry.dtd">
<album name="public">
    <author name="Юрий Сударьков">
        <verse id="1">
            <title>Как жаль...</title>
            <date>24-Feb-1994</date>
            <text><![CDATA[
Как жаль
        Что блеклым словом
                          "красота"
Я не сумею выразить 
                    любовь
К оврагу
        К лесу
              К небу
                    К облакам
К весне
       К капели
               К лужам
                      и к тебе...
            ]]></text>
            <link></link>
        </verse>
        <verse id="2">
            <title>Чем жил?</title>
            <date>29-Jun-1993</date>
            <text><![CDATA[
Чем жил?
Ловил в сосуды
Своего 
       молчанья капли
Или грибы любви на спицы
Hанизывал как чеки...

Поэтому сошел с ума
         от вздоха птицы
Упавшего
        цветком
               в ладонь...
            ]]></text>
            <link></link>
        </verse>

        <verse id="3">
            <title>Утро, солнце, ветер, птица...</title>
            <date>17-Dec-1993</date>
            <text><![CDATA[
Утро
    солнце
          ветер
               птица...
У реки склонюсь напиться
Пусть меня волною смоет
Поплыву - неси, водица
            ]]></text>
            <link></link>
        </verse>

        <verse id="4">
            <title>Кошка</title>
            <date>22-Mar-1993</date>
            <text><![CDATA[
Дождь...
Влажной
       теплой лапой
Ступает кошка
             по карнизу 
                       ощущений
            ]]></text>
            <link></link>
        </verse>
        <verse id="5">
            <title>Кавказ</title>
            <date>26-Aug-1993</date>
            <text><![CDATA[
Эта листва меня
В лоб целует. Я
Чувствую жар огня

Плети травы, звеня
Хлещут ноги коня

И ветер
       Hа флейте
                Ушных 
                     раковин
Фальшивит 
         "Полет шмеля"...
            ]]></text>
            <link></link>
        </verse>
        <verse id="6">
            <title>Шум столетий</title>
            <date>13-Feb-1995</date>
            <text><![CDATA[
1. Камень на камень - шум столетий
   Мутный поток несется к обрыву
   Наш корабль разбился в щепки
   Кто-то остался, кто-то - сгинул

2. Река жизни несется дыбясь
   Бросая волны навстречу ветру
   Порвется любая тугая привязь
   Если мы не верны обету
            ]]></text>
            <link></link>
        </verse>
        <verse id="7">
            <title>Очарование</title>
            <date>Apr-1994</date>
            <text><![CDATA[
Очарование - порыв ветра,
Нежданный гость в тихую погоду,
Сорвет шляпу и стихнет где-то,
Оставив нас лицом к заходу...
            ]]></text>
            <link></link>
        </verse>
        <verse id="8">
            <title>Не спешу...</title>
            <date>27-Apr-1993</date>
            <text><![CDATA[
Не спешу!
А надо бы?

Не спешу?
А надо бы!

Не спешу,
А надо бы!

Не спе...
А надо было!
            ]]></text>
            <link></link>
        </verse>
        <verse id="9">
            <title>Как стать драконом</title>
            <date>Nov-1992</date>
            <text><![CDATA[
Встаньте
      Лицом против ветра
Дайте
      Огню поглотить сигарету
Выдох
      Окутает дымом сферу
Разум
      Оценит дракона
            ]]></text>
            <link></link>
        </verse>
        <verse id="10">
            <title>Огненный шар</title>
            <date>Aug-1992</date>
            <text><![CDATA[
Касается гор
Огненный шар
Спускается с гор
Белый пожар
Готовые видеть
Чувствуют жар
Сердца...
            ]]></text>
            <link></link>
        </verse>
        <verse id="11">
            <title>Легко Воспламеняемая Жидкость</title>
            <date>29-Mar-1993</date>
            <text><![CDATA[
Моя кровь -
         элвэжэ
Tэ вспышки -
         тридцать шесть
Меня лишь тронь,
         и я уже
Дышу огнем, 
         вздымаю шерсть...
            ]]></text>
            <link></link>
        </verse>
        <verse id="12">
            <title>Грация</title>
            <date>03-May-1993</date>
            <text><![CDATA[
В рыданьи Грация,
(Увы, не на моем граните)
Лохматость мысли
Посвятит ветрам.
            ]]></text>
            <link></link>
        </verse>
        <verse id="13">
            <title>Как холодно...</title>
            <date>18-Dec-1995</date>
            <text><![CDATA[
Как холодно
Как холодно и пусто
Грустно
Тоска зудит бока
И кажется века она уж длится
Злится
Пустая суета!
Умчаться прочь
Проститься
С этим домом, с этой птицей
Навеки
Навсегда!
            ]]></text>
            <link></link>
        </verse>
        <verse id="15">
            <title>Маленькая девочка</title>
            <date>Apr-1994</date>
            <text><![CDATA[
Маленькая девочка
С длинною косичкой
Бегает по берегу
Брызгает водичкой
Хлопает в ладоши
Топает ножкой
До чего прелестная
Девочка-хорошка
            ]]></text>
            <link></link>
        </verse>
        <verse id="16">
            <title>Маленькая женщина</title>
            <date>10-Dec-1998</date>
            <text><![CDATA[
В каждом движении
                 Стебля
В каждом вздохе
                 Ветра
Прячется маленькая
                 Женщина
            ]]></text>
            <link></link>
        </verse>
        <verse id="17">
            <title>Твой сияюще-бледный лик...</title>
            <date>Jan-1993</date>
            <text><![CDATA[
Твой сияюще-бледный лик
Как луна купается
    в воде моих воспоминаний
Милая,
    я узнал
           твою обратную сторону
            ]]></text>
            <link></link>
        </verse>
        <verse id="18">
            <title>Милый мой друг</title>
            <date>10-Nov-1994</date>
            <text><![CDATA[
Разумеется, милый мой друг,
Я тебя провожу до моста.
Разумеется, милый мой, да!
Чувства выдаст скупая слеза.

Мое слабое сердце стучит.
Все стучит, и стучит, и стучит...
Ничего-то в нем слабого нет.
Разве песня? И та не молчит.

Песня-дой, что родилась сама.
Эту песню пою я тебе.
Как в реке голубая вода,
Льется песня само по себе.

Впрочем, я уже много сказал.
Уходи, милый друг, уходи.
Ты пройдешь все земные пути
И поймешь, что со мной потерял.
            ]]></text>
            <link></link>
        </verse>
        <verse id="19">
            <title>Норма</title>
            <date>06-Oct-1992</date>
            <text><![CDATA[
Норма 
     вмещающая вечность...

     Слагающая мифы
осторожность...

Дерзость
     объемная как небо...

     Грезящее расцветом
лето...

Счастье
     мощенное камнями
     вмещенное огнями...

Норма...
            ]]></text>
            <link></link>
        </verse>
        <verse id="20">
            <title>Давай запомним</title>
            <date>Oct-1998</date>
            <text><![CDATA[
Давай запомним наши отношения как чудо, которое уже не сможем повторить.
Запомним слова, произнесенные в порыве любовной страсти и в тиши объятий.
Запомним все, что освещало нашу жизнь - не будем помнить обид.
Не будем помнить ссор. Уходи... Не дай мне повода ненавидеть тебя.
Не дай мне повода забыть тебя, как кошмарный сон... Уходи...
            ]]></text>
            <link></link>
        </verse>
        <verse id="21">
            <title>Река</title>
            <date>15-Feb-1994</date>
            <text><![CDATA[
Река, как кошка, свои бока
Лижет шершавой волной.
И, лишь я усну, умоет река
Звезды одну за одной.
            ]]></text>
            <link></link>
        </verse>
        <verse id="22">
            <title>Повод</title>
            <date>13-Feb-1995</date>
            <text><![CDATA[
Я твержу который день кряду
Дорогая, на дворе слякоть
Надевай, пожалуйста, шляпку!
А она не надевает - бяка!
            ]]></text>
            <link></link>
        </verse>
        <verse id="23">
            <title>Роберт</title>
            <date>23-Feb-1995</date>
            <text><![CDATA[
Я прошу и нет конца просьбам
Я прошу подать пальто, шапку
Отварить пельмени или манты
А она не чешется - ей жалко

Я прошу который день к ряду
Я прошу, а на душе слякоть
Потому что все-равно Роберт
Не получит ничего, явно!
            ]]></text>
            <link></link>
        </verse>
        <verse id="24">
            <title>Укол шипом розы</title>
            <date>03-May-1993</date>
            <text><![CDATA[
Кончики пальцев святятся током.
Касание кисти уносит потоком
Мысли, желания, белое, черное...
Время проносится в миг. Заведенное
Серое облако, черного белое,
Скачет по небу как оголтелое.
Тонкие ноги врастают в педали.
Шар головы небесные дали
Дикообразом колючих волос
Скребет оставляя десятки полос...
Красного цвета липкая жидкость
Солнце презрев, в небе светится.
Капает в реки, живность терзая...

Время кончалось, боль исчезала,
Переставал давать себя знать
Укол Шипом Розы...
            ]]></text>
            <link></link>
        </verse>
        <verse id="25">
            <title>Россия</title>
            <date>02-Sep-1993</date>
            <text><![CDATA[
Вековых лесов махровая щетина
Пронзает небо синим глазом.
Hаследница угасшей Византии
Сияет неотточенным алмазом.
Грандиозна, полярна, неповторяема
Hовых времен мессия.
Океаном неукротимым вздымается
Яхонтово-парчевая Россия!
            ]]></text>
            <link></link>
        </verse>
        <verse id="26">
            <title>Матрос</title>
            <date>04-Feb-1999</date>
            <text><![CDATA[
Матрос хронически недоползал
Матрос терялся в сферах томных
Его прокуренный вокзал
Кипел толпою монотонной

Кипел и плавился асфальт
Сползала к носу бескозырка
Две сотни ярдов до воды
Полугнилая роба в дырках

И ничего, что море спит
И корабли стоят на рейде
Еще один всего-лишь миг
И доползет матрос, не сдрейфит

И доползет, и прокричит
Катись к чертям бутылка рома
Матрос за стойкой снова спит
Пол-жизни длится рейс до дома
